ALVARA_DATA = {
    "1ª Categoria - Edifícios e património construído": [
        {"name": "1.ª - Estruturas e elementos de betão", "class": ""},
        {"name": "2.ª - Estruturas metálicas", "class": ""},
        {"name": "3.ª - Estruturas de madeira", "class": ""},
        {"name": "4.ª - Alvenarias, rebocos e assentamento de cantarias", "class": ""},
        {"name": "5.ª - Estuques, pinturas e outros revestimentos", "class": ""},
        {"name": "6.ª - Carpintarias", "class": ""},
        {"name": "7.ª - Trabalhos em perfis não estruturais", "class": ""},
        {"name": "8.ª - Canalizações e condutas em edifícios", "class": ""},
        {"name": "9.ª - Instalações sem qualificação específica", "class": ""},
        {"name": "10.ª - Restauro de bens imóveis histórico-artísticos", "class": ""},
    ],
    "2ª Categoria - Vias de comunicação, obras de urbanização e outras infraestruturas": [
        {"name": "1.ª - Vias de circulação rodoviária e aeródromos", "class": ""},
        {"name": "2.ª - Vias de circulação ferroviária", "class": ""},
        {"name": "3.ª - Pontes e viadutos de betão", "class": ""},
        {"name": "4.ª - Pontes e viadutos metálicos", "class": ""},
        {"name": "5.ª - Obras de arte correntes", "class": ""},
        {"name": "6.ª - Saneamento básico", "class": ""},
        {"name": "8.ª - Calcetamentos", "class": ""},
        {"name": "9.ª - Ajardinamentos", "class": ""},
        {"name": "10.ª - Infraestruturas de desporto e lazer", "class": ""},
        {
            "name": "11.ª - Sinalização não elétrica e dispositivos de proteção e segurança",
            "class": "",
        },
    ],
    "3ª Categoria - Obras hidráulicas": [
        {"name": "1.ª - Obras fluviais e aproveitamentos hidráulicos", "class": ""},
        {"name": "2.ª - Obras portuárias", "class": ""},
        {"name": "3.ª - Obras de proteção costeira", "class": ""},
        {"name": "4.ª - Barragens e diques", "class": ""},
        {"name": "5.ª - Dragagens", "class": ""},
        {"name": "6.ª - Emissários", "class": ""},
    ],
    "4ª Categoria - Instalações elétricas e mecânicas": [
        {
            "name": "1.ª - Instalações elétricas de utilização de baixa tensão com potência até 50 kVA",
            "class": "",
        },
        {"name": "2.ª - Postos de transformação até 250 KVA", "class": ""},
        {"name": "3.ª - Postos de transformação acima de 250 kVA", "class": ""},
        {
            "name": "4.ª - Redes e instalações elétricas de tensão de serviço até 30 kV",
            "class": "",
        },
        {
            "name": "5.ª - Redes e instalações elétricas de tensão de serviço acima de 30 kV",
            "class": "",
        },
        {
            "name": "6.ª - Instalações de produção de energia elétrica até 30 kV",
            "class": "",
        },
        {
            "name": "7.ª - Instalações de produção de energia elétrica acima de 30 kV",
            "class": "",
        },
        {"name": "8.ª - Instalações de tração elétrica", "class": ""},
        {"name": "9.ª - Infraestruturas de telecomunicações", "class": ""},
        {
            "name": "10.ª - Sistemas de extinção de incêndios, de segurança e de deteção",
            "class": "",
        },
        {"name": "11.ª - Instalações de elevação", "class": ""},
        {
            "name": "12.ª - Aquecimento, ventilação, ar condicionado e refrigeração",
            "class": "",
        },
        {"name": "13.ª - Estações de tratamento ambiental", "class": ""},
        {"name": "16.ª - Redes de ar comprimido e vácuo", "class": ""},
        {
            "name": "17.ª - Instalações de apoio e sinalização em sistemas de transportes",
            "class": "",
        },
        {"name": "18.ª - Gestão técnica centralizada", "class": ""},
        {"name": "19.ª - Outras instalações mecânicas e eletromecânicas", "class": ""},
    ],
    "5ª Categoria - Outros trabalhos": [
        {"name": "1.ª - Demolições", "class": ""},
        {"name": "2.ª - Movimentação de terras", "class": ""},
        {"name": "3.ª - Túneis e outros trabalhos de geotécnica", "class": ""},
        {"name": "4.ª - Fundações especiais", "class": ""},
        {"name": "5.ª - Reabilitação de elementos estruturais de betão", "class": ""},
        {"name": "6.ª - Paredes de contenção e ancoragens", "class": ""},
        {"name": "7.ª - Drenagens e tratamento de taludes", "class": ""},
        {"name": "8.ª - Armaduras para betão armado", "class": ""},
        {
            "name": "9.ª - Reparações e tratamentos superficiais em estruturas metálicas",
            "class": "",
        },
        {"name": "10.ª - Cofragens", "class": ""},
        {"name": "11.ª - Impermeabilizações e isolamentos", "class": ""},
        {"name": "12.ª - Andaimes e outras estruturas provisórias", "class": ""},
        {"name": "13.ª - Caminhos agrícolas e florestais", "class": ""},
    ],
}
